export const COLOR = {
  
  // COMMON
  FOCUESED_COLOR: "#707070",
  NOT_FOCUESD_COLOR: "#EEEEEE",
  HEADER_BACKGROUND_COLOR: "#F8F8F8",
  BACKGROUND_COLOR: "#FFFFFF",

  //LOGIN & JOIN
  FONT_COLOR: "#707070",
  BORDER_OUTER_COLOR : "#707070",
  BORDER_INNER_COLOR: "#EEEEEE",

  //BOTTOM_TAB
  BOTTOMTAB_FOCUSED_COLOR: "#EEEEEE",
  BOTTOMTAB_NOT_FOCUSED_COLOR: "#FFFFFF",
  BOTTOMTAB_OUTER_COLOR: "#707070",

  //HOME
  HOME_HEADER_ALERT_DOT_COLOR: "#FF0000",

  //CREATE
  CREATE_RECIEPS_THUMNAIL_INNER_LABEL_COLOR: "#ACACAC",
  CREATE_RECIPES_BODER_INNER_COLOR : "#F8F8F8",
  CREATE_RECIEPS_BORDER_OUTER_COLOR: "#ACACAC",
  CREATE_INPUT_TEXT_BORDER_OUTER_COLOR: "#B9B9B9",
  CREATE_INPUT_TEXT_BORDER_INNTER_COLOR: "#F8F8F8",
  
  CREATE_RECIPE_SUB_STAGE_NOT_SELECT_COLOR: "#F8F8F8",
  CREATE_RECIPE_SUB_STAGE_SELECT_COLOR: "#DADADA",
  CREATE_RECIPE_SUB_STAGE_OUTER_COLOR: "#707070",
  
  //VIEW
  RECIPE_OUTER_BORDER_COLOR: "#B9B9B9",
  RECIPE_INNER_BACKGROUND_COLOR : "#F8F8F8",
  RECIPE_INNER_INNER_BACKGROUND_COLOR: "#EEEEEE",

  //ALERT
  ALERT_MOVE_BORDER_BOTTOM_NOT_VISIBLE_COLOR : "#EEEEEE",
  ALERT_MOVE_BORDER_BOTTOM_VISIBLE_COLOR: "#707070",
  ALERT_ACCEPT_BUTTON_BACKGROUND_COLOR: "#EEEEEE",
  ALERT_REJECT_BUTTON_OUTER_COLOR: "#707070",
  ALERT_NICKNAME_LABEL_COLOR: "#1296B0",
  ALERT_CONTAINER_BOTTOM_COLOR: "#C0C0C0",
  
  //INFO
  INFO_PLUS_BORDER_OUTER_COLOR: "#B9B9B9",
  INFO_PLUS_BORDER_INNER_COLOR: "#F8F8F8",
  INFO_PID_AND_LIST_BORDER_INNTER_COLO : "#EEEEEE",
}