version: "3"
services:
    necipe:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4000:4000"
        volumes: 
            - /usr/src/app/node_modules
            - ./:/usr/src/app
        stdin_open: true
